eticaret/urls.py
from django.contrib import admin
from django.urls import path,include
from Catalog import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('Catalog/',include("Catalog.urls")),
    path('user/',include("user.urls")),
    path('order/',include("order.urls")),
    

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "order"

urlpatterns = [

   path('cart/',views.view_cart,name="view_cart"),
   path('addtocart/<int:product_id>/',views.addtocart,name="addtocart"),
   path('lessstock/<int:id>/',views.lessStock,name="lessStock"),
   path('addstock/<int:id>',views.addStock,name="addStock"),
   path('remove/<int:id>/',views.remove,name="remove"),

   
   path('payment/',views.payment,name="payment"),
   path('complete_order/<int:id>',views.complete_order,name="complete_order"),
   path('orders/',views.orders,name="orders"),
   path('orders/<int:id>',views.order_detail,name="order_detail"),
   path('users_orders/<int:id>',views.users_orders,name="users_orders"),
   path('order/',views.order,name="order"),


   path('add_address/',views.add_address,name="add_address"),
   path('view_address/',views.view_address,name="view_address"),
   path('update_address/<int:id>/', views.update_address, name='update_address'),
   path('delete_address/<int:id>/',views.delete_address,name="delete_address"),


   path('users/',views.users,name="users"),




   path('cargos/',views.cargos,name="cargos"),
   path('create_cargos/',views.create_cargos,name="create_cargos"),
   path('create_cargo/<int:id>',views.create_cargo,name="create_cargo"),



   
    
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "user"   

urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('update_account/',views.update_account,name="update_account"),
    path('account/',views.account,name="account"),
    

    

]

user/models.py
from django.db import models

# Create your models here.

order/forms.py
from django import forms
from .models import Cart,CartItem,Adres
from django.core.exceptions import ValidationError



class CartItemForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = ['product', 'quantity',] 


class AdresForm(forms.ModelForm):
    class Meta:
        model = Adres
        
        fields= ['title','name_lastname','phoneNumber','eposta','adres']

        labels = {
            'title': 'Adres Başlığı',
            'name_lastname': 'İsim ve Soyisim',
            'phoneNumber': 'Telefon Numarası',
            'eposta': 'E-Posta',
            'adres': 'Adres Bilgileri',
        }


        def clean(self):
            cleaned_data = super().clean()

            phoneNumber = cleaned_data.get('phoneNumber')
            title = cleaned_data.get('title')
            adres= cleaned_data.get('adres')
            name_lastname = cleaned_data.get('name_lastname')
            eposta = cleaned_data.get('eposta')

            if phoneNumber and len(phoneNumber) != 10:
                raise ValidationError("Telefon numarası 10 haneli olmalıdır.")
            
            if title and len(title) < 3:
                raise ValidationError("Lütfen 3 veya daha fazla karakter giriniz.")
            
            if adres and len(adres) <1 :
                raise ValidationError("Lütfen bir adres giriniz.")
            
            if name_lastname and len(name_lastname) < 5:
                raise ValidationError("Lütfen 5 veya daha fazla karakter giriniz.")
            
            
            return cleaned_data

user/forms.py
from typing import Any
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    
    username = forms.CharField(label="Kullanıcı Adı")
    password = forms.CharField(label="Parola",widget=forms.PasswordInput)




class UserForm(forms.ModelForm):
    class Meta:
        model = User

        fields = ["first_name","last_name","email"]
    
        labels = {

            'first_name' : 'İsim',
            'last_name' : 'Soyisim',
            'email': 'E-Mail',


        }

        def clean(self) :
            cleaned_data = super().clean()

            first_name = self.cleaned_data("first_name")
            last_name = self.cleaned_data("last_name")
            email = self.changed_data("email")

            if first_name and len(first_name)<2:
                raise ValueError("En az 2 karakterli bir isim girmelisiniz.")
            if last_name and len(last_name)<2:
                raise ValueError("En az 2 karakterli bir soyisim girmelisiniz.")



            return cleaned_data

    
class RegisterForm(forms.Form):
    
    username = forms.CharField(max_length=50,label = "Kullanıcı Adı")
    password = forms.CharField(max_length=25,label="Parola",widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=25,label="Parolayı Doğrula",widget=forms.PasswordInput)

    def clean(self):

        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm  and password!=confirm:
            raise forms.ValidationError("Parolalar eşleşmiyor..")
        
        values = {

            "username":username,
            "password":password,

        }

        return values 

order/views.py
from django.shortcuts import render, redirect ,get_object_or_404,get_list_or_404
from .models import Cart, CartItem ,OrderItem, Order,Adres,Shipment
from Catalog.models import Product
from .forms import CartItem,AdresForm
from django.contrib.auth.decorators import login_required,user_passes_test
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.decorators.http import require_POST
from decimal import Decimal


#Sepet
@login_required
@user_passes_test(lambda u: not u.is_superuser)
def view_cart(request):


    user_cart, created = Cart.objects.get_or_create(user=request.user)
    cart_items = user_cart.cartitem_set.all()
    
    total_price = sum(int(item.product.unitPrice) * item.quantity for item in cart_items)
    return render(request, 'cart.html', {'cart_items': cart_items, 'total_price': total_price,})


#Sepete Ekle
@user_passes_test(lambda u: not u.is_superuser)
def addtocart(request, product_id):
    if request.method == 'POST':
        
        product = Product.objects.get(id=product_id)
        
        user_cart, created = Cart.objects.get_or_create(user=request.user)

        cart_item, created = CartItem.objects.get_or_create(cart=user_cart, product=product)
           

    return redirect('order:view_cart')
    

#Sipariş Adetini arttır
@user_passes_test(lambda u: not u.is_superuser)
def addStock(request, id):
   
    cart_items = CartItem.objects.filter(id=id)

    cart_item = cart_items.first()
    

    cart_item.quantity+=1
    cart_item.save()

    
 
    return redirect('order:view_cart')

#Sipariş adetini azalt
@user_passes_test(lambda u: not u.is_superuser)
def lessStock(request,id):
    
    cart_items = CartItem.objects.filter(id=id)
    cart_item = cart_items.first()

    if cart_item.quantity>1:
        cart_item.quantity-=1
        cart_item.save()
    else:
        messages.info(request,"Ürün adeti en az 1 olabilir. Ürünü kaldırmak için lütfen sil'e tıklayınız..")
    
 
    return redirect('order:view_cart')


#Sepetten çıkar
@user_passes_test(lambda u: not u.is_superuser)
def remove(request, id):
    cart_item = get_object_or_404(CartItem, id=id)
    cart_item.delete()
    messages.success(request, "Ürün başarıyla silindi")
    return redirect('order:view_cart')







#Ödeme sayfası
@user_passes_test(lambda u: not u.is_superuser)
def payment(request):

    adres= Adres.objects.filter(user=request.user)

    context = {
        "adres":adres
    }


    return render(request,'payment.html',context=context)








#Kullanıcının Siparişleri
def orders(request):

    user = request.user
    order = Order.objects.filter(user=user)
    

    context = {
        "order": order

    }

    return render(request, 'orders.html', context=context)


#Tüm siparişler
@user_passes_test(lambda u:  u.is_superuser)
def order(request): 

    order = Order.objects.all()
    context={
        "order":order
    }
    return render(request,'order.html',context=context)



#Siparişi tamamla gibi bişey
@user_passes_test(lambda u: not u.is_superuser)
@login_required
def complete_order(request,id):
    user = request.user

   
    

    try:
        cart = Cart.objects.get(user=user)
    except Cart.DoesNotExist:
        messages.error(request, "Sepetiniz bulunamadı.")
        return redirect("order:view_cart")
    
    try:
        adres = Adres.objects.get(user=user,id=id)
    except Adres.DoesNotExist:
        messages.error(request,"Lütfen teslimat adresi ekleyiniz.")
        return redirect("order:view_address")
    
    
    title=str(adres.title)
    name_lastname=str(adres.name_lastname)
    adres=str(adres.adres)

    order = Order.objects.create(user=user, status='Bekliyor',title=title,adres=adres,name_lastname=name_lastname)

   


    for cart_item in CartItem.objects.filter(cart=cart):

        price = Decimal(cart_item.product.unitPrice) * cart_item.quantity

        if cart_item.product.unitsInStock < cart_item.quantity:
            messages.error(request, f"{cart_item.product.productName} için yeterli stok bulunmamaktadır. Mevcut stok: {cart_item.product.unitsInStock}")
            raise ValueError("Yetersiz stok")

        OrderItem.objects.create(
            order=order,
            product=cart_item.product,
            quantity=cart_item.quantity,
            price=price,
        )
        cart_item.product.unitsInStock -= cart_item.quantity
        cart_item.product.save()

    cart.cartitem_set.all().delete()

    messages.success(request,"Sipariş başarıyla oluşturuldu")
    return redirect("order:view_cart")




#Sipariş Detayı
def order_detail(request, id):

    


    user = request.user
    order = Order.objects.get(id=id)

    if order.user!=user and user.is_superuser!=True:
        messages.info(request,"Size ait olmayan bir siparişin detayını görüntüleyemezsiniz..")
        return redirect('order:orders')
    
        
    item = OrderItem.objects.filter(order=order)
    
    

    return render(request, 'order_detail.html', {'order': order, 'item': item})









#Adresler Sayfası
@user_passes_test(lambda u: not u.is_superuser)
def view_address(request):
    user = request.user
    adres =Adres.objects.filter(user=user)

    context = {

        "adres" : adres
    }

    return render(request,"view_address.html",context=context)


#Adres Ekle
@user_passes_test(lambda u: not u.is_superuser)
def add_address(request):
    if request.method == 'POST':
        form = AdresForm(request.POST)
        if form.is_valid():
            address = form.save(commit=False)
            address.user = request.user
            address.save()
            messages.success(request,"Adres başarıyla kaydedildi")
            return render(request, 'view_address.html')
    else:
        form = AdresForm()
    
    return render(request, 'add_address.html', {'form': form})


#Adres Güncelle
@user_passes_test(lambda u: not u.is_superuser)
def update_address(request, id):
    
    address = get_object_or_404(Adres, id=id, user=request.user)

    if request.method == 'POST':
        
        form = AdresForm(request.POST, instance=address)
        if form.is_valid():
            
            form.save()
            messages.success(request,"Adres başarıyla güncellendi")
            return redirect('order:view_address')
    else:
        form = AdresForm(instance=address)
    
    return render(request, 'update_address.html', {'form': form})




#Adres Sil
@user_passes_test(lambda u: not u.is_superuser)
def delete_address(request,id):

    address = get_object_or_404(Adres, id=id, user=request.user)
    address.delete()

    messages.success(request,"Adres başarıyla silindi")
    return redirect("order:view_address")





@user_passes_test(lambda u: u.is_superuser)
#Kargoları görüntüle (bekliyor olanları)
def create_cargos(request):

    pending_order = Order.objects.filter(status="Bekliyor")
    context = {
        "order": pending_order

    }

    return render(request, 'create_cargos.html', context=context)


#Tüm Kargolar
@user_passes_test(lambda u: u.is_superuser)
def cargos(request):

    cargos = Shipment.objects.all()
    context = {
        "cargos": cargos

    }

    return render(request, 'cargos.html', context=context)



@user_passes_test(lambda u: u.is_superuser)
#Kargoyu oluştur
def create_cargo(request,id):

    order = get_object_or_404(Order, id=id)

    
    new_shipment = Shipment.objects.create(
        user=request.user,
        order=order,
        status='Kargoya verildi'
    )

    order.status="Kargoya Verildi"
    order.save()

    messages.success(request,"Kargo oluşturuldu")

    return redirect('order:cargos')




#Kullanıcılar
@user_passes_test(lambda u: u.is_superuser)
def users(request):

    user = User.objects.all()
    context = {
        "user":user
    }
    return render(request,'user.html',context=context)
    
#Kullanıcının siparişleri
def users_orders(request, id):
    user = get_object_or_404(User, id=id)
  
    order = Order.objects.filter(user=user)
    
    context = {
        "order": order
    }


    return render(request, 'users_orders.html', context)

user/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import RegisterForm,LoginForm,UserForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout

# Create your views here.

def register(request):

    form = RegisterForm(request.POST or None)
    if form.is_valid():

        
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        newUser = User(username = username)
        newUser.set_password(password)

        newUser.save()
        login(request,newUser)
        messages.success(request,"Başarıyla Kayıt Oldunuz.")

        return redirect("index")
    context = {
        "form":form
        }
    return render(request,"register.html",context)

        

def account(request):

    return render(request,"account.html")


def update_account(request):

    user = request.user
    
    if request.method == "POST":
        form = UserForm(request.POST, instance=user)

        if form.is_valid():
            form.save()
            
            messages.success(request,"Hesap bilgileri başarıyla güncellendi..")
            return redirect('user:account')
        
    else:
        form = UserForm(instance=user)

    return render(request,"update_account.html",{"form":form})





def loginUser(request):
    
    form = LoginForm(request.POST or None)

    context = {

        "form" : form
    }

    if form.is_valid():



        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username, password=password)
        
        if user is None:

            messages.info(request,"Kullanıcı adı veya şifre yanlış")
            return render(request,"login.html",context)
        
        messages.success(request,"Başarıyla giriş yapıldı")
        login(request,user)
        return redirect("index")
    return render(request,"login.html",context)




def logoutUser(request):
    logout(request)
    messages.success(request,"Başarıyla Çıkış Yaptınız")
    return redirect("index")

templates/account.html
{% extends "layout.html" %}
{% block body %}


<h3 style="text-align: center;font-family:fantasy;">Hesap Bilgilerim</h3>
<hr>
<br>


{% if user.is_authenticated %}
<div class="card" style="margin-inline-start:200px;margin-inline-end: 200px;">
    <div class="card-header" style="font-weight:bold;">
      Hesabım
    </div>
    <div class="card-body">
      <p class="card-title" style="font-weight: lighter;">Kullanıcı adı: {{user.username}}</p>
      <p class="card-text" style="font-weight: lighter;">İsim: {{user.first_name}}</p>
      <p class="card-text" style="font-weight: lighter;">Soyisim: {{user.last_name}}</p>
      <p class="card-text" style="font-weight: lighter;">E-Posta: {{user.email}}</p>
      <hr>
      <br>
      <a href="/user/update_account/" class="btn btn-success" style="font-size: x-small;">Güncelle</a> 
    </div>
  </div>
  
  
  
  
  </ul>
  <br>
  <br><br><br><br>
  <br><br><br><br>





{% endif %}






















{% endblock body %}

templates/add_address.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}
<div class="row">
    
    <h2>Adres Ekle</h2>
    <hr>
     <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" style="font-size: x-small;">Kaydet</button>
    </form>
    
   
  </div>
  <br><br><br><br><br>
        
   


{% endblock body %}

templates/categories.html
{% extends "layout.html" %}

{% block body %}

<h3 style="text-align: center;font-family:fantasy;">Kategoriler</h3><br>

<br>
{% if category %}

<div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Kategori</th>
        <th scope="col">Ürünler</th>
        <th scope="col">Güncelle</th>
        <th scope="col">Kaldır</th>
      </tr>
    </thead>
    <tbody>
      {% for category in category %}
      <tr>
      <tr>
        <th scope="row" style="color: rgb(54, 80, 255);font-family:arial;font-size:small;padding-top:15px;">
          {{ category.id }}</a></th>
        <td style="font-size:small;"><strong>{{ category.categoryName }}</strong></td>
        <td><a href="/Catalog/category/{{category.id}}"  class="btn btn-primary" style="font-size: x-small;">İncele</a></td>  
        <td><a href="/Catalog/update_category/{{category.id}}"  class="btn btn-warning" style="font-size: x-small;">Güncelle</a></td>  
        <td><a href="/Catalog/delete_category/{{category.id}}"  class="btn btn-danger" style="font-size: x-small;"><i class="bi bi-trash3"></i></a></td> 
      </tr>
      {% endfor %}

    </tbody>
  </table>
</div>


{% else %}

<p style="font-weight: unset;font-style: italic;">Henüz bir kategori oluşturmadınız.</p>
<br>


{% endif %}
<br>


<a href="/Catalog/add_category/" class="btn btn-success" style="font-size: small;">Ekle <i class="bi bi-plus-circle-fill"></i></a>
<br>
<br>
<br><br><br>


{% endblock body %}

templates/create_cargos.html
{% extends "layout.html" %}
{% block body %}



<h2 style="text-align: center;font-style:initial;font-family: fantasy;">Siparişleri Kargola</h2>
<br>

<br>
{% if order %}
<div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Sipariş No</th>
                <th scope="col">Sipariş Durumu</th>
                <th scope="col">Sipariş Tarihi</th>
                <th scope="col">Kullanıcı</th>
                <th scope="col">Kargoya Ver</th>
            </tr>
        </thead>
        <tbody>
            {% for order in order %}
            <tr>
                <th scope="row" style="color: rgb(54, 80, 255);font-family:arial;font-size:small;padding-top:15px;">
                    <a href="{% url 'order:order_detail' order.id %}">C#{{ order.id }}</a>
                </th>
                <td style="font-size:small;">{{ order.status }}</td>
                <td style="font-size:small;">{{ order.created_at }}</td>
                <td style="font-size:small;">{{ request.user.username }}  #{{request.user.id}}</td>
                <td>
                    <a href="{% url 'order:create_cargo' order.id %}" class="btn btn-warning"
                        style="font-size: x-small;">Kargola</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<p style="font-weight: unset;font-style: italic;">Henüz bir sipariş yok</p>
<br><br><br><br><br>
{% endif %}
{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}
<!-- <h6>

    {% if request.user.is_authenticated %}

   <em> Hoşgeldiniz: </em>  {{request.user.username}} 

    {% else %}

    Giriş Yapılmadı


    {% endif %}

</h3> -->
    




<header class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/wfh8dDlNFOk/1600x900')">
    <div class="text-center my-5">
        <h1 class="text-white fs-3 fw-bolder">PC Lab</h1>
        <p class="text-white-50 mb-0">Hoşgeldiniz..</p>
    </div>
</header>
<!-- Content section-->
<section class="py-5">
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <h2> <strong>Hoş Geldiniz!</strong></h2>
                <p class="lead">Bilgisayar tutkunları için bir cennete hoş geldiniz! Burası, teknolojiyle dolu bir
                    dünyanın kapılarını aralayan bir platform. Her bir tuşa dokunuşta heyecan verici bir yolculuğa
                    çıkacağınız bir alan sunuyoruz. Bilgisayar parçaları, donanım ve yazılım dünyasının kalbinin attığı
                    yerde, sizinle birlikte olmaktan büyük mutluluk duyuyoruz.</p>
                <p class="mb-0">Burası sadece bir alışveriş platformu değil, aynı zamanda bilgi paylaşımının,
                    deneyimlerin ve tutkunun bir araya geldiği bir topluluk merkezi. Sizi, yeni teknolojilerin ve
                    yenilikçi ürünlerin heyecan verici dünyasına götürecek yolda bizimle birlikte olmaya davet ediyoruz.
                </p>
            </div>
        </div>
    </div>
</section>

<div class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/4ulffa6qoKA/1200x800')">

    <div style="height: 20rem"></div>
</div>

<section class="py-5">
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <h2><strong>Bizimle Keşfet</strong></h2>
                <p class="lead">Bizimle keşfedin, öğrenin ve ilham alın. Sizin için tasarladığımız bu platformda,
                    bilgisayarınızı her seferinde bir adım daha ileriye taşımanın heyecanını birlikte yaşayalım!</p>
                <p class="mb-0">Başlayın ve teknoloji yolculuğunuzda bize katılın!</p>
            </div>
        </div>
    </div>
</section>





{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.3/font/bootstrap-icons.min.css">

    <title>PC Lab</title>
    {% block head %}{% endblock head %}



</head>

<body>
    {% include "includes/navbar.html" %}
    {% include "includes/secondnavbar.html" %}
    {% include "includes/thirdnavbar.html" %}





    <div style="margin-top: 100px;" class="container">


        {% if messages %}

        {% for message in messages %}
        {% if message.tags == "info" %}
        <div class="alert alert-danger">{{ message }}</div>

        {% else %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>


        {% endif %}

        {% endfor %}

        {% endif %}
        {% block body %}

        {% endblock %}

    </div>


    {% include "includes/footer.html" %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>

</html>

templates/login.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}

<h3 style="font-family: fantasy;">Giriş Yap</h3>
<hr>
<br>

<form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <br>
    <button type="submit" class="btn btn-primary" style="font-size:small;">Giriş Yap</button>
</form>


{% endblock body %}

templates/order.html
{% extends "layout.html" %}

{% block body %}

<h3 style="text-align: center;font-family:fantasy;">Tüm Siparişler</h3>
<hr>
<br>
{% if order %}

<div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Sipariş No</th>
        <th scope="col">Kullanıcı</th>
        <th scope="col">Sipariş Durumu</th>
        <th scope="col">Sipariş Tarihi</th>
        <th scope="col">Detay</th>
        
      </tr>
    </thead>
    <tbody>
      {% for order in order %}
      <tr>
      <tr>
        <th scope="row" style="color: rgb(54, 80, 255);font-family:arial;font-size:small;padding-top:15px;">
          {{ order.id }}</a></th>
        <td style="font-size:small;">{{ order.user.username }}</td>
        <td style="font-size:small;">{{ order.status }}</td>
        <td style="font-size:small;">{{ order.created_at }}</td>
        <td><a href="/order/orders/{{ order.id }}" class="btn btn-success" style="font-size: x-small;"> İncele</a></td>
      </tr>
      {% endfor %}

    </tbody>
  </table>
</div>


{% else %}

<p style="font-weight: unset;font-style: italic;">Henüz bir sipariş yok.</p>


{% endif %}





{% endblock body %}

templates/payment.html
{% extends "layout.html" %}
{% block body %}
<div class="container">
  <h3 style="font-family: fantasy;">Sepetim > Ödeme </h2>


</div>


<form method="post">
  {% csrf_token %}

  <div class="form-group">
    <label for="card_number">Kredi Kartı Numaranız:</label>
    <input type="text" id="card_number" name="card_number" class="form-control" required>
  </div>
  <div class="form-group">
    <label for="expiry_date">Son Kullanma Tarihi:</label>
    <input type="text" id="expiry_date" name="expiry_date" class="form-control" placeholder="MM/YY" required>
  </div>
  <div class="form-group">
    <label for="cvv">CVV:</label>
    <input type="text" id="cvv" name="cvv" class="form-control" required>
  </div>
  <br>

</form>
<br>
<br>

<h5 style="font-family: fantasy;">Adres Seçimi</h5>
<h5 style="font-size: small;font-weight: bold;font-style: italic;">*** Seçeceğiniz adrese tıkladığınızda sipariş
  oluşacaktır ***</h5>

<hr>
{% for adres in adres %}


<div class="list-group">
  <a href="{% url 'order:complete_order' adres.id %}" class="list-group-item list-group-item-action "
    aria-current="true">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">{{adres.title}}</h5>
      <small>{{adres.name_lastname}}</small>
    </div>
    <p class="mb-1">info: {{adres.adres}}</p>
    <small>E-Posta: {{adres.eposta}}</small>
    <br>
    <small>Tel: +90 {{adres.phoneNumber}}</small>
  </a>
  <br>

</div>

{% endfor %}


<br><br><br>

<br><br><br>

</div>
{% endblock %}

templates/update_account.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}



<h3 style="font-family: fantasy;">Bilgileri Güncelle</h3>
     <hr>
     <br>

    <form method="post" enctype="multipart/form-data"> 
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" style="font-size: small;">Güncelle</button>
    </form>

    <br><br><br><br><br>




{% endblock body %}